In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 


C:\Users\ABC\AppData\Local\Temp\ipykernel_17144\3388369714.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [2]:
a=pd.read_csv("advertising.csv")
a

Daily Time Spent on Site  Age  Area Income  Daily Internet Usage  \
0                       68.95   35     61833.90                256.09   
1                       80.23   31     68441.85                193.77   
2                       69.47   26     59785.94                236.50   
3                       74.15   29     54806.18                245.89   
4                       68.37   35     73889.99                225.58   
..                        ...  ...          ...                   ...   
995                     72.97   30     71384.57                208.58   
996                     51.30   45     67782.17                134.42   
997                     51.63   51     42415.72                120.37   
998                     55.55   19     41920.79                187.95   
999                     45.01   26     29875.80                178.35   

                             Ad Topic Line            City  Male  \
0       Cloned 5thgeneration orchestration     Wrightburgh     0   
1       Monitored national standardization       West Jodi     1   
2         Organic bottom-line service-desk        Davidton     0   
3    Triple-buffered reciprocal time-frame  West Terrifurt     1   
4            Robust logistical utilization    South Manuel     0   
..                                     ...             ...   ...   
995          Fundamental modular algorithm       Duffystad     1   
996        Grass-roots cohesive monitoring     New Darlene     1   
997           Expanded intangible solution   South Jessica     1   
998   Proactive bandwidth-monitored policy     West Steven     0   
999        Virtual 5thgeneration emulation     Ronniemouth     0   

                    Country            Timestamp  Clicked on Ad  
0                   Tunisia  2016-03-27 00:53:11              0  
1                     Nauru  2016-04-04 01:39:02              0  
2                San Marino  2016-03-13 20:35:42              0  
3                     Italy  2016-01-10 02:31:19              0  
4                   Iceland  2016-06-03 03:36:18              0  
..                      ...                  ...            ...  
995                 Lebanon  2016-02-11 21:49:00              1  
996  Bosnia and Herzegovina  2016-04-22 02:07:01              1  
997                Mongolia  2016-02-01 17:24:57              1  
998               Guatemala  2016-03-24 02:35:54              0  
999                  Brazil  2016-06-03 21:43:21              1  

[1000 rows x 10 columns]

In [3]:
a.head()

Daily Time Spent on Site  Age  Area Income  Daily Internet Usage  \
0                     68.95   35     61833.90                256.09   
1                     80.23   31     68441.85                193.77   
2                     69.47   26     59785.94                236.50   
3                     74.15   29     54806.18                245.89   
4                     68.37   35     73889.99                225.58   

                           Ad Topic Line            City  Male     Country  \
0     Cloned 5thgeneration orchestration     Wrightburgh     0     Tunisia   
1     Monitored national standardization       West Jodi     1       Nauru   
2       Organic bottom-line service-desk        Davidton     0  San Marino   
3  Triple-buffered reciprocal time-frame  West Terrifurt     1       Italy   
4          Robust logistical utilization    South Manuel     0     Iceland   

             Timestamp  Clicked on Ad  
0  2016-03-27 00:53:11              0  
1  2016-04-04 01:39:02              0  
2  2016-03-13 20:35:42              0  
3  2016-01-10 02:31:19              0  
4  2016-06-03 03:36:18              0

In [4]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Daily Time Spent on Site  1000 non-null   float64
 1   Age                       1000 non-null   int64  
 2   Area Income               1000 non-null   float64
 3   Daily Internet Usage      1000 non-null   float64
 4   Ad Topic Line             1000 non-null   object 
 5   City                      1000 non-null   object 
 6   Male                      1000 non-null   int64  
 7   Country                   1000 non-null   object 
 8   Timestamp                 1000 non-null   object 
 9   Clicked on Ad             1000 non-null   int64  
dtypes: float64(3), int64(3), object(4)
memory usage: 78.3+ KB


In [5]:
from sklearn.model_selection import train_test_split

In [6]:
x=a[['Daily Time Spent on Site','Age','Area Income','Daily Internet Usage','Male']]
y=a['Clicked on Ad']

In [7]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33,random_state=42)

In [8]:
from sklearn.linear_model import LogisticRegression

In [9]:
logmodel=LogisticRegression()
logmodel.fit(x_train,y_train)

C:\Users\ABC\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [10]:
predictions=logmodel.predict(x_test)

In [11]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,predictions))
print(confusion_matrix(y_test,predictions))

              precision    recall  f1-score   support

           0       0.86      0.96      0.91       162
           1       0.95      0.85      0.90       168

    accuracy                           0.90       330
   macro avg       0.91      0.90      0.90       330
weighted avg       0.91      0.90      0.90       330

[[155   7]
 [ 25 143]]


In [12]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()
model.fit(x_train,y_train)
predict=(model.predict(x_test))
print(predict)
print(classification_report(y_test,predict))
print(confusion_matrix(y_test,predict))


[1 1 1 1 0 1 0 1 0 1 0 1 1 0 1 1 1 1 0 1 0 1 1 0 0 1 1 0 1 1 0 1 0 1 1 0 0
 1 1 1 0 1 1 1 0 0 1 1 0 1 1 0 1 0 0 0 0 1 0 1 0 1 0 1 1 1 1 0 1 1 1 1 1 0
 1 1 0 1 1 0 1 1 1 1 0 0 1 0 0 0 0 1 0 1 0 0 1 1 0 0 1 0 1 0 1 0 1 0 1 0 1
 0 1 1 0 1 0 1 0 1 1 1 1 0 1 0 1 0 0 1 1 1 1 0 1 0 0 1 0 1 0 0 1 1 0 1 1 0
 0 0 0 0 1 0 1 0 1 0 0 0 1 1 0 0 1 0 0 0 0 0 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1
 1 0 1 1 1 0 1 0 0 1 0 1 1 0 1 0 0 0 0 1 0 1 0 0 0 0 1 1 1 1 0 0 1 0 1 0 1
 1 1 0 0 0 0 0 0 1 1 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 1 1 1
 0 0 1 1 1 1 0 0 0 0 1 1 0 1 0 1 0 1 0 0 0 1 0 0 1 1 0 0 0 1 1 0 0 1 0 0 1
 0 1 1 0 0 1 0 1 1 0 0 1 0 0 1 1 1 0 1 0 0 0 0 0 1 1 1 1 0 0 0 1 0 0]
              precision    recall  f1-score   support

           0       0.93      0.93      0.93       162
           1       0.93      0.93      0.93       168

    accuracy                           0.93       330
   macro avg       0.93      0.93      0.93       330
weighted avg       0.93      0.93      0.93       330

[[1

In [13]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier()
model.fit(x_train,y_train)
predict=model.predict(x_test)
print(confusion_matrix(y_test,predict))
print(classification_report(y_test,predict))

[[156   6]
 [  9 159]]
              precision    recall  f1-score   support

           0       0.95      0.96      0.95       162
           1       0.96      0.95      0.95       168

    accuracy                           0.95       330
   macro avg       0.95      0.95      0.95       330
weighted avg       0.95      0.95      0.95       330



In [14]:
from sklearn.neighbors import KNeighborsClassifier
model=KNeighborsClassifier(n_neighbors=6)
model=RandomForestClassifier()
model.fit(x_train,y_train)
predict=model.predict(x_test)
print(confusion_matrix(y_test,predict))
print(classification_report(y_test,predict))

[[156   6]
 [ 10 158]]
              precision    recall  f1-score   support

           0       0.94      0.96      0.95       162
           1       0.96      0.94      0.95       168

    accuracy                           0.95       330
   macro avg       0.95      0.95      0.95       330
weighted avg       0.95      0.95      0.95       330



In [16]:
a=sns.load_dataset("iris")
a

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [18]:
x=a[['sepal_length','sepal_width','petal_length','petal_width']]
y=a['species']


In [19]:
from sklearn.model_selection import train_test_split



In [20]:
x_train,x_test,y_train,y_test=train_test_split(x,y)


In [21]:
x_train


sepal_length  sepal_width  petal_length  petal_width
131           7.9          3.8           6.4          2.0
67            5.8          2.7           4.1          1.0
149           5.9          3.0           5.1          1.8
24            4.8          3.4           1.9          0.2
69            5.6          2.5           3.9          1.1
..            ...          ...           ...          ...
30            4.8          3.1           1.6          0.2
126           6.2          2.8           4.8          1.8
41            4.5          2.3           1.3          0.3
114           5.8          2.8           5.1          2.4
37            4.9          3.6           1.4          0.1

[112 rows x 4 columns]

In [22]:
y_train


131     virginica
67     versicolor
149     virginica
24         setosa
69     versicolor
          ...    
30         setosa
126     virginica
41         setosa
114     virginica
37         setosa
Name: species, Length: 112, dtype: object

In [23]:
x_test


sepal_length  sepal_width  petal_length  petal_width
90            5.5          2.6           4.4          1.2
142           5.8          2.7           5.1          1.9
29            4.7          3.2           1.6          0.2
79            5.7          2.6           3.5          1.0
141           6.9          3.1           5.1          2.3
129           7.2          3.0           5.8          1.6
122           7.7          2.8           6.7          2.0
56            6.3          3.3           4.7          1.6
82            5.8          2.7           3.9          1.2
7             5.0          3.4           1.5          0.2
115           6.4          3.2           5.3          2.3
92            5.8          2.6           4.0          1.2
54            6.5          2.8           4.6          1.5
49            5.0          3.3           1.4          0.2
133           6.3          2.8           5.1          1.5
108           6.7          2.5           5.8          1.8
103           6.3          2.9           5.6          1.8
47            4.6          3.2           1.4          0.2
121           5.6          2.8           4.9          2.0
65            6.7          3.1           4.4          1.4
48            5.3          3.7           1.5          0.2
118           7.7          2.6           6.9          2.3
120           6.9          3.2           5.7          2.3
81            5.5          2.4           3.7          1.0
39            5.1          3.4           1.5          0.2
100           6.3          3.3           6.0          2.5
72            6.3          2.5           4.9          1.5
36            5.5          3.5           1.3          0.2
44            5.1          3.8           1.9          0.4
146           6.3          2.5           5.0          1.9
1             4.9          3.0           1.4          0.2
112           6.8          3.0           5.5          2.1
11            4.8          3.4           1.6          0.2
22            4.6          3.6           1.0          0.2
125           7.2          3.2           6.0          1.8
59            5.2          2.7           3.9          1.4
143           6.8          3.2           5.9          2.3
2             4.7          3.2           1.3          0.2

In [24]:
y_test


90     versicolor
142     virginica
29         setosa
79     versicolor
141     virginica
129     virginica
122     virginica
56     versicolor
82     versicolor
7          setosa
115     virginica
92     versicolor
54     versicolor
49         setosa
133     virginica
108     virginica
103     virginica
47         setosa
121     virginica
65     versicolor
48         setosa
118     virginica
120     virginica
81     versicolor
39         setosa
100     virginica
72     versicolor
36         setosa
44         setosa
146     virginica
1          setosa
112     virginica
11         setosa
22         setosa
125     virginica
59     versicolor
143     virginica
2          setosa
Name: species, dtype: object

In [25]:
from sklearn.linear_model import LogisticRegression


In [26]:
model=LogisticRegression()


In [27]:
model.fit(x_train,y_train)


LogisticRegression()

In [28]:
predictions=model.predict(x_test)


In [29]:
predictions


array(['versicolor', 'virginica', 'setosa', 'versicolor', 'virginica',
       'virginica', 'virginica', 'versicolor', 'versicolor', 'setosa',
       'virginica', 'versicolor', 'versicolor', 'setosa', 'versicolor',
       'virginica', 'virginica', 'setosa', 'virginica', 'versicolor',
       'setosa', 'virginica', 'virginica', 'versicolor', 'setosa',
       'virginica', 'versicolor', 'setosa', 'setosa', 'virginica',
       'setosa', 'virginica', 'setosa', 'setosa', 'virginica',
       'versicolor', 'virginica', 'setosa'], dtype=object)

In [30]:
from sklearn.metrics import confusion_matrix,classification_report

In [31]:
print(classification_report(y_test,predictions))


              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        12
  versicolor       0.91      1.00      0.95        10
   virginica       1.00      0.94      0.97        16

    accuracy                           0.97        38
   macro avg       0.97      0.98      0.97        38
weighted avg       0.98      0.97      0.97        38



In [32]:
print(confusion_matrix(y_test,predictions))

[[12  0  0]
 [ 0 10  0]
 [ 0  1 15]]
