In [ ]:
!py -m pip install numpy


Defaulting to user installation because normal site-packages is not writeable
  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/16/2e/86f24451c2d530c88daf997cb8d6ac622c1d40d19f5a031ed68a4b73a374/numpy-1.26.4-cp312-cp312-win_amd64.whl.metadata
     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ---------------------------------------- 0.0/61.0 kB ? eta -:--:


[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
import numpy as np

In [ ]:
#list to numpy array(np.array is method)
a=[1,2,3]
import numpy as np
arr=np.array(a)
arr

array([1, 2, 3])

In [ ]:
matrix=[[1,2,3],[4,5,6],[7,8,9]]
mat=np.array(matrix)
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.zeros?

Docstring:
zeros(shape, dtype=float, order='C', *, like=None)

Return a new array of given shape and type, filled with zeros.

Parameters
----------
shape : int or tuple of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of zeros with the given shape, dtype, and order.

See Al

In [ ]:
np.linspace(0,100)

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [ ]:
np.random.rand(5)

array([0.80103715, 0.22144909, 0.42936952, 0.74247426, 0.94239371])

In [ ]:
a=[1,2,3,4,5,6]
arr=np.min(a)

arr

1

In [ ]:
arr=np.max(a)
arr

6

In [ ]:
argmin=np.argmin(a)
argmin

0

In [ ]:
argmax=np.argmax(a)
argmax

5

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [ ]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [ ]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [ ]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.rand(25)

array([0.9413712 , 0.33988518, 0.49393596, 0.2164049 , 0.71452543,
       0.0234738 , 0.2991528 , 0.19965153, 0.03878339, 0.10890398,
       0.61868897, 0.64472809, 0.30923997, 0.83581043, 0.35617231,
       0.76593476, 0.52211862, 0.01860478, 0.20942765, 0.527045  ,
       0.60702295, 0.45420847, 0.62815456, 0.56096552, 0.86977375])

In [ ]:
np.random.rand(1)

array([0.17420933])

In [ ]:
np.arange(1,101).reshape(10,10)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [ ]:
oneD=np.arange(0,12)
oneD

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
twoD=np.arange(1,101).reshape(10,10)
twoD

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [ ]:
threeD=np.arange(0,12).reshape(3,2,2)
threeD

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [ ]:
np.empty((3,3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
datatype=threeD.dtype
datatype

dtype('int32')

In [ ]:
oneD.shape

(12,)

In [ ]:
twoD.shape


(10, 10)

In [ ]:
threeD.shape

(3, 2, 2)

In [ ]:
oneD.ndim

1

In [ ]:
twoD.ndim

2

In [ ]:
threeD.ndim

3

In [ ]:
oneD=np.zeros(12)
oneD

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
twoD=np.zeros((12,12))
twoD

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
m=np.random.randint(1,100,20)
m

array([33, 10, 98, 33, 38, 40, 96, 34, 82, 52,  4, 57, 59, 98, 48, 45, 98,
       91, 64, 91])

In [ ]:
x=np.sort(m)
x

array([ 4, 10, 33, 33, 34, 38, 40, 45, 48, 52, 57, 59, 64, 82, 91, 91, 96,
       98, 98, 98])

In [ ]:
x=np.flip(m)
x

array([91, 64, 91, 98, 45, 48, 98, 59, 57,  4, 52, 82, 34, 96, 40, 38, 33,
       98, 10, 33])

In [ ]:
np.eye(5,5).reshape(25,)

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [ ]:
one=np.arange(0,9).reshape(3,3)
two=np.arange(9,12)
three=np.append(one,two).reshape(4,3)
three

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
!py -m pip install pandas


Defaulting to user installation because normal site-packages is not writeable
  Obtaining dependency information for pandas from https://files.pythonhosted.org/packages/87/03/fe50521919aa981f6a1c197037da4623a267b0e5f42246d69ba048e86da3/pandas-2.2.0-cp312-cp312-win_amd64.whl.metadata
  Obtaining dependency information for pytz>=2020.1 from https://files.pythonhosted.org/packages/9c/3d/a121f284241f08268b21359bd425f7d4825cffc5ac5cd0e1b3d82ffd2b10/pytz-2024.1-py2.py3-none-any.whl.metadata
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.5 MB 163.8 kB/s eta 0:01:10
   ---------------------------------------- 0.0/11.5 MB 163.8 kB/s eta 0:01:10
   ---------------------------------------- 0.0/11.5 MB 140.3 kB/s eta 0


[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
import pandas as pd
marks=pd.Series([30,40,50],index=["python","dsa","Dbms"])
marks

C:\Users\ABC\AppData\Local\Temp\ipykernel_9928\1130572907.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


python    30
dsa       40
Dbms      50
dtype: int64

In [ ]:
type(marks)

pandas.core.series.Series

In [ ]:
mydict={"name":'mahir',"course":'BCA',"address":"vadodara"}
pd.Series(mydict)

name          mahir
course          BCA
address    vadodara
dtype: object

In [ ]:
mydict.keys()

dict_keys(['name', 'course', 'address'])

In [ ]:
mydict.values()

dict_values(['mahir', 'BCA', 'vadodara'])

In [ ]:
import numpy as np
np.random.seed(1)
df=pd.DataFrame(np.random.randint(1,100,(5,3)),index=["mahir","meet","dev","Rahul","heet"],columns=["python","DSA","RDBMS"])
df

python  DSA  RDBMS
mahir      38   13     73
meet       10   76      6
dev        80   65     17
Rahul       2   77     72
heet        7   26     51

In [ ]:
df['total']=df['python']+df['DSA']+df['RDBMS']
df


python  DSA  RDBMS  total
mahir      38   13     73    124
meet       10   76      6     92
dev        80   65     17    162
Rahul       2   77     72    151
heet        7   26     51     84

In [ ]:
df["RDBMS"]

mahir    73
meet      6
dev      17
Rahul    72
heet     51
Name: RDBMS, dtype: int32

In [ ]:
df[["python","RDBMS"]]

python  RDBMS
mahir      38     73
meet       10      6
dev        80     17
Rahul       2     72
heet        7     51

In [ ]:
df.loc["mahir"]

python     38
DSA        13
RDBMS      73
total     124
Name: mahir, dtype: int32

In [ ]:
df.loc[["mahir","meet"]]

python  DSA  RDBMS  total
mahir      38   13     73    124
meet       10   76      6     92

In [ ]:
df.iloc[3]

python      2
DSA        77
RDBMS      72
total     151
Name: Rahul, dtype: int32

In [ ]:
df["name"]=["pooja","dev","mahir","naitik","teerth"]
df

python  DSA  RDBMS  total    name
mahir      38   13     73    124   pooja
meet       10   76      6     92     dev
dev        80   65     17    162   mahir
Rahul       2   77     72    151  naitik
heet        7   26     51     84  teerth

In [ ]:
df.set_index("name")

python  DSA  RDBMS  total
name                             
pooja       38   13     73    124
dev         10   76      6     92
mahir       80   65     17    162
naitik       2   77     72    151
teerth       7   26     51     84

In [ ]:
df['percentage']=df['total']/3
df

python  DSA  RDBMS  total  percentage
mahir      38   13     73    124   41.333333
meet       10   76      6     92   30.666667
dev        80   65     17    162   54.000000
Rahul       2   77     72    151   50.333333
heet        7   26     51     84   28.000000

In [ ]:
df

python  DSA  RDBMS  total  percentage
mahir      38   13     73    124   41.333333
meet       10   76      6     92   30.666667
dev        80   65     17    162   54.000000
Rahul       2   77     72    151   50.333333
heet        7   26     51     84   28.000000

In [ ]:
df.drop('percentage',axis=1,inplace=True)

In [ ]:
df

python  DSA  RDBMS  total
mahir      38   13     73    124
meet       10   76      6     92
dev        80   65     17    162
Rahul       2   77     72    151
heet        7   26     51     84

In [ ]:
df2=pd.read_csv("mahir.csv")
df2

(12001  Gujarat   10       29  12002  Unnamed: 5
0     Maharashtra       19   36  12003.0    NaN         NaN
1       Rajasthan       13   31  12004.0    NaN         NaN
2  Madhya Pradesh       14   21  12005.0    NaN         NaN
3          Punjab       12   13  12006.0    NaN         NaN
4       Karnataka       23   31  12007.0    NaN         NaN
5       Tamilnadu       25   29   1208.0    NaN         NaN
6          Kerala       21  15)      NaN    NaN         NaN