In [3]:
import numpy as np
x=np.arange(10).reshape(5,2)
y=range(5)

range(0, 5)

In [4]:
x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [8]:
list(y)

[0, 1, 2, 3, 4]

In [11]:
!py -m pip install sklearn


Defaulting to user installation because normal site-packages is not writeable
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'


  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
      rather than 'sklearn' for pip commands.
      
      Here is how to fix this error in the main use cases:
      - use 'pip install scikit-learn' rather than 'pip install sklearn'
      - replace 'sklearn' by 'scikit-learn' in your pip requirements files
        (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
      - if the 'sklearn' package is used by one of your dependencies,
        it would be great if you take some time to track which package uses
        'sklearn' instead of 'scikit-learn' and report it to their issue tracker
      - as a last resort, set the environment variable
        SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error
      
      More information is available at
      https://github.com/scikit-learn/sklearn-

In [24]:
from sklearn.model_selection import LinearRegression

ImportError: cannot import name 'LinearRegression' from 'sklearn.model_selection' (C:\Users\ABC\AppData\Roaming\Python\Python312\site-packages\sklearn\model_selection\__init__.py)

In [19]:
from sklearn.model_selection import train_test_split

In [16]:
!py -m pip install -U scikit-learn

Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [20]:
x_train,x_test,y_train,y_test=train_test_split(x,y)

In [21]:
x_train

array([[4, 5],
       [2, 3],
       [6, 7]])

In [22]:
x_test

array([[8, 9],
       [0, 1]])

In [23]:
y_train

[2, 1, 3]

In [24]:
y_test

[4, 0]

In [26]:
from sklearn.linear_model import LinearRegression

In [2]:
import pandas as pd
a=pd.read_csv('USA_Housing.csv')
a

Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
0         79545.458574             5.682861                   7.009188   
1         79248.642455             6.002900                   6.730821   
2         61287.067179             5.865890                   8.512727   
3         63345.240046             7.188236                   5.586729   
4         59982.197226             5.040555                   7.839388   
...                ...                  ...                        ...   
4995      60567.944140             7.830362                   6.137356   
4996      78491.275435             6.999135                   6.576763   
4997      63390.686886             7.250591                   4.805081   
4998      68001.331235             5.534388                   7.130144   
4999      65510.581804             5.992305                   6.792336   

      Avg. Area Number of Bedrooms  Area Population         Price  \
0                             4.09     23086.800503  1.059034e+06   
1                             3.09     40173.072174  1.505891e+06   
2                             5.13     36882.159400  1.058988e+06   
3                             3.26     34310.242831  1.260617e+06   
4                             4.23     26354.109472  6.309435e+05   
...                            ...              ...           ...   
4995                          3.46     22837.361035  1.060194e+06   
4996                          4.02     25616.115489  1.482618e+06   
4997                          2.13     33266.145490  1.030730e+06   
4998                          5.44     42625.620156  1.198657e+06   
4999                          4.07     46501.283803  1.298950e+06   

                                                Address  
0     208 Michael Ferry Apt. 674\nLaurabury, NE 3701...  
1     188 Johnson Views Suite 079\nLake Kathleen, CA...  
2     9127 Elizabeth Stravenue\nDanieltown, WI 06482...  
3                             USS Barnett\nFPO AP 44820  
4                            USNS Raymond\nFPO AE 09386  
...                                                 ...  
4995                   USNS Williams\nFPO AP 30153-7653  
4996              PSC 9258, Box 8489\nAPO AA 42991-3352  
4997  4215 Tracy Garden Suite 076\nJoshualand, VA 01...  
4998                          USS Wallace\nFPO AE 73316  
4999  37778 George Ridges Apt. 509\nEast Holly, NV 2...  

[5000 rows x 7 columns]

In [5]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Avg. Area Income              5000 non-null   float64
 1   Avg. Area House Age           5000 non-null   float64
 2   Avg. Area Number of Rooms     5000 non-null   float64
 3   Avg. Area Number of Bedrooms  5000 non-null   float64
 4   Area Population               5000 non-null   float64
 5   Price                         5000 non-null   float64
 6   Address                       5000 non-null   object 
dtypes: float64(6), object(1)
memory usage: 273.6+ KB


In [6]:
a.describe()

Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
count       5000.000000          5000.000000                5000.000000   
mean       68583.108984             5.977222                   6.987792   
std        10657.991214             0.991456                   1.005833   
min        17796.631190             2.644304                   3.236194   
25%        61480.562388             5.322283                   6.299250   
50%        68804.286404             5.970429                   7.002902   
75%        75783.338666             6.650808                   7.665871   
max       107701.748378             9.519088                  10.759588   

       Avg. Area Number of Bedrooms  Area Population         Price  
count                   5000.000000      5000.000000  5.000000e+03  
mean                       3.981330     36163.516039  1.232073e+06  
std                        1.234137      9925.650114  3.531176e+05  
min                        2.000000       172.610686  1.593866e+04  
25%                        3.140000     29403.928702  9.975771e+05  
50%                        4.050000     36199.406689  1.232669e+06  
75%                        4.490000     42861.290769  1.471210e+06  
max                        6.500000     69621.713378  2.469066e+06

In [7]:
a.columns

Index(['Avg. Area Income', 'Avg. Area House Age', 'Avg. Area Number of Rooms',
       'Avg. Area Number of Bedrooms', 'Area Population', 'Price', 'Address'],
      dtype='object')

In [10]:
x=a[['Avg. Area Income', 'Avg. Area House Age', 'Avg. Area Number of Rooms',
       'Avg. Area Number of Bedrooms', 'Area Population']]
y=a['Price']

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.4,random_state=101)

In [13]:
x_train

Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
1303      68091.179676             5.364208                   7.502956   
1051      75729.765546             5.580599                   7.642973   
4904      70885.420819             6.358747                   7.250241   
931       73386.407340             4.966360                   7.915453   
4976      75046.313791             5.351169                   7.797825   
...                ...                  ...                        ...   
4171      56610.642563             4.846832                   7.558137   
599       70596.850945             6.548274                   6.539986   
1361      55621.899104             3.735942                   6.868291   
1547      63044.460096             5.935261                   5.913454   
4959      75078.791516             7.644779                   8.440726   

      Avg. Area Number of Bedrooms  Area Population  
1303                          3.10     44557.379656  
1051                          4.21     29996.018448  
4904                          5.42     38627.301473  
931                           4.30     38413.490484  
4976                          5.23     34107.888619  
...                            ...              ...  
4171                          3.29     25494.740298  
599                           3.10     51614.830136  
1361                          2.30     63184.613147  
1547                          4.10     32725.279544  
4959                          4.33     56148.449322  

[3000 rows x 5 columns]

In [14]:
x_test

Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
1718      66774.995817             5.717143                   7.795215   
2511      62184.539375             4.925758                   7.427689   
345       73643.057298             6.766853                   8.337085   
2521      61909.041438             6.228343                   6.593138   
54        72942.705059             4.786222                   7.319886   
...                ...                  ...                        ...   
1776      65173.050438             7.679469                   6.602618   
4269      42969.659393             6.295501                   7.885507   
1661      48735.924512             5.543730                   6.091906   
2410      65081.584048             5.433570                   9.212518   
2302      65969.707036             7.325976                   8.020966   

      Avg. Area Number of Bedrooms  Area Population  
1718                          4.32     36788.980327  
2511                          6.22     26008.309124  
345                           3.34     43152.139577  
2521                          4.29     28953.925377  
54                            6.41     24377.909049  
...                            ...              ...  
1776                          4.23     44125.540782  
4269                          4.38     29594.089863  
1661                          2.43     19682.347295  
2410                          5.14     37594.493458  
2302                          4.09     61772.756810  

[2000 rows x 5 columns]

In [15]:
y_train

1303    1.489648e+06
1051    1.183015e+06
4904    1.547889e+06
931     1.186442e+06
4976    1.340344e+06
            ...     
4171    7.296417e+05
599     1.599479e+06
1361    1.102641e+06
1547    8.650995e+05
4959    2.108376e+06
Name: Price, Length: 3000, dtype: float64

In [16]:
y_test

1718    1.251689e+06
2511    8.730483e+05
345     1.696978e+06
2521    1.063964e+06
54      9.487883e+05
            ...     
1776    1.489520e+06
4269    7.777336e+05
1661    1.515271e+05
2410    1.343824e+06
2302    1.906025e+06
Name: Price, Length: 2000, dtype: float64

In [17]:
from sklearn.linear_model import LinearRegression


In [19]:
model1=LinearRegression()

In [20]:
model1.fit(x_train,y_train)

LinearRegression()

In [21]:
prediction=model1.predict(x_test)

In [22]:
prediction

array([1260960.70567627,  827588.75560329, 1742421.24254344, ...,
        372191.40626917, 1365217.15140898, 1914519.5417888 ])

In [23]:
y_test

1718    1.251689e+06
2511    8.730483e+05
345     1.696978e+06
2521    1.063964e+06
54      9.487883e+05
            ...     
1776    1.489520e+06
4269    7.777336e+05
1661    1.515271e+05
2410    1.343824e+06
2302    1.906025e+06
Name: Price, Length: 2000, dtype: float64